---
name: ci_validate_submodules

on:
  pull_request:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v7
        with:
          submodules: recursive
